### ISSUE TITLE
Settings save port button crashes the app

### ISSUE THREAD

**Issue by Apollo-Roboto** [Antoni-Czaplicki/SteamVR.HA-Agent#1]
Looks like there is an oversight on the save button as it crashes the app every time I click it making it impossible to change the port.

To reproduce:
Click the save button.

Do you have any log output I can link here?

---

I Love this project, keep up the good work!

**Comment by Antoni-Czaplicki** [comment]
Fixed in [v0.0.5](https://github.com/Antoni-Czaplicki/SteamVR.HA-Agent/releases/tag/0.0.5), thanks for the report
